name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      distribution: # 定义 distribution 输入
        description: 'Distribution option'
        required: true
        default: 'internal' # 设置默认值，可以根据你的需求修改

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Build with Gradle
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseName: Release ${{ github.sha }}
          distribution: ${{ github.event.inputs.distribution }} # 在这里使用输入的值
