name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17' # 适用于你的项目

      - name: Build with Gradle
        run: ./gradlew assembleDebug # 根据你的项目需要执行正确的 Gradle 构建命令

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug # 根据你的项目需要给 APK 取一个合适的名字
          path: app/build/outputs/apk/debug/app-debug.apk # 根据你的项目路径配置

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: github.ref == 'refs/heads/master'
        with:
          files: |
            app/build/outputs/apk/debug/app-debug.apk # 根据你的项目需要发布的 APK 路径
          token: ${{ secrets.GITHUB_TOKEN }}
          releaseName: Release ${{ github.sha }}
